class exercise

write the code for the following matrix multiplication and visualize the same in tensorflow

150   250   750
500   600   800              *             [390  890      790]^ T
900   200   450




In [0]:
import tensorflow as tf

In [0]:
m1 = tf.Variable([[150,250,750],[500,600,800],[900,200,450]])

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
m2= tf.Variable([[390],[890],[790]])

In [0]:
sess=tf.Session()

In [0]:
init_op=tf.global_variables_initializer()

In [0]:
sess.run(init_op)

In [0]:
sess.run(m1)

array([[150, 250, 750],
       [500, 600, 800],
       [900, 200, 450]], dtype=int32)

In [0]:
sess.run(m2)

array([[390],
       [890],
       [790]], dtype=int32)

In [0]:
resut=tf.matmul(m1,m2)

In [0]:
sess.run(resut)

array([[ 873500],
       [1361000],
       [ 884500]], dtype=int32)

**RESHAPE**


In [0]:
x=tf.Variable([50,2,3,10,4,5,6,7])

In [0]:
y=tf.Variable([[1,2],[3,4],[5,6]])

In [0]:
z=tf.Variable([[1,9],[8,2],[8,7]])

In [0]:
sess=tf.Session()

In [0]:
init_op = tf.global_variables_initializer()

In [0]:
sess.run(init_op)

In [0]:
sess.run(x)

array([50,  2,  3, 10,  4,  5,  6,  7], dtype=int32)

In [0]:
x.shape

TensorShape([Dimension(8)])

In [0]:
sess.run(y)

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [0]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

In [0]:
sess.run(tf.reshape(y,[2,3]))

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [0]:
#sess.run(tf.reshape(z,[2,3]))
sess.run(tf.reshape(z,[1,1,6]))
#sess.run(tf.reshape(z,[]))

array([[[1, 9, 8, 2, 8, 7]]], dtype=int32)

## **MAX VALUE**

In [0]:
sess.run(x)

array([50,  2,  3, 10,  4,  5,  6,  7], dtype=int32)

In [0]:
sess.run(tf.argmax(x,axis=0))

0

In [0]:
sess.run(z)

array([[1, 9],
       [8, 2],
       [8, 7]], dtype=int32)

In [0]:
sess.run(tf.argmax(z,axis=0))

array([1, 0])

In [0]:
sess.run(tf.argmax(z,axis=1))

array([1, 0, 0])